### ISSUE TITLE
Internet explorer 11

### ISSUE THREAD

**Issue by glaggia-larus** [ghiden/angucomplete-ie8#1]
In our project internet explorer 11 shows the snippet always open. I think there was a fix for this in the -alt version, can you please create a fix for the ie8 version also?

**Comment by ghiden** [comment]
Try this branch:
https://github.com/ghiden/angucomplete-ie8/tree/fix-ie-11-initial-value
Just copy the js file and test it.

**Comment by ghiden** [comment]
Released v0.1.2.
